### ISSUE TITLE
Redelegate cli command critical error

### ISSUE THREAD

**Issue by doodleoo3** [initia-labs/initia#184]
**Describe the bug**
There is a problem with a transaction build. The redelegate command via CLI is not working correctly and when sending the command we get the SOURCE address and DESTINATION address are SAME.

**To Reproduce**
1. Run redelegarion CLI comand. 
Example: initiad tx mstaking redelegate <src_address> <dist_address> 16000000000uinit --from wallet --chain-id initiation-1 --gas 400000 --fees 600000uinit --chain-id initiation-1
2. See error(same src and dist adresses):
```
auth_info:
  fee:
    amount:
    - amount: "600000"
      denom: uinit
    gas_limit: "400000"
    granter: ""
    payer: ""
  signer_infos: []
  tip: null
body:
  extension_options: []
  memo: ""
  messages:
  - '@type': /initia.mstaking.v1.MsgBeginRedelegate
    amount:
    - amount: "16000000000"
      denom: uinit
    delegator_address: init18gcqgg7lpn2vzzevul3a98uq5mk8vpdqyk0m3d
    validator_dst_address: initvaloper18gtqadftw9pfqv6x2svwdqkfsw7hjptdj6xp0h
    validator_src_address: initvaloper18gtqadftw9pfqv6x2svwdqkfsw7hjptdj6xp0h
  non_critical_extension_options: []
  timeout_height: "0"
signatures: []
```

**Expected behavior**
For the command to work correctly, the recipient and sender addresses must be different.

**Screenshots**
![image](https://github.com/initia-labs/initia/assets/106701127/9097ce78-abe3-4722-b083-fea6f01956d6)

```
https://scan.testnet.initia.xyz/initiation-1/txs/8E0FE31C38067252D2823127E7CA005850ED5C2EB39AFF278B9B1644A52F2FE3
```
![image](https://github.com/initia-labs/initia/assets/106701127/d7c58971-5647-4112-b84d-3199c163dc84)
